markdown: kramdown

# File exclusions
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Site settings
url: 'https://sagerpascal.github.io'
title: 'Pascal Sager'
description: 'My thoughts, my ideas, my projects - or at least a few of them'
permalink: pretty

sass:
    sass_dir: _sass